### ISSUE TITLE
Server crashes with ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by a-mckinley** [UniqueVision/plpgsql-lsp#43] opened 2022-06-15 10:43 UTC
## Describe the bug

I am unable to easily determine what SQL code is causing this issue as there is no context in the error message.

The error message before the server crash is:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "value" argument must be one of type number or string or an instance of Buffer or Uint8Array. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at bidirectionalIndexOf (node:buffer:954:9)
    at Uint8Array.indexOf (node:buffer:960:10)
    at t.findIndexFromBuffer (/home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:42:8458)
    at l (/home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:1:10168)
    at /home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:1:11961
    at Array.flatMap (<anonymous>)
    at t.parseCreateStatements (/home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:1:11321)
    at t.parseDefinitions (/home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:30:996)
    at async t.DefinitionsManager.innerUpdateDocumentDefinitions (/home/alastair/.vscode/extensions/uniquevision.vscode-plpgsql-lsp-2.7.2-linux-x64/server/out/server.js:24:2916) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
## Environment

- [x] Linux

**Comment by yas7010uv** [comment] 2022-07-01 10:13
@a-mckinley
Sorry for the delay in noticing.

We will investigate the cause.

**Comment by a-mckinley** [comment] 2022-07-01 10:19
FYI I am using PG14

**Comment by yas7010uv** [comment] 2022-07-05 12:47
@a-mckinley 
Today we release [v2.8.2](https://github.com/UniqueVision/plpgsql-lsp/tree/v2.8.2), enhancing the error log message. 
This release does not resolve parse errors, please tell us your unparsed code sample.

**Comment by a-mckinley** [comment] 2022-07-05 14:20
At first glance it appears that this error is gone in v2.8.2.

**Comment by yas7010uv** [comment] 2022-07-05 14:38
That's good! Close this issue once.

**Closed by yas7010uv** 2022-07-05 14:38 UTC
